/**
 * ============================================================================
 *  VOICE PANEL — the full loop: record -> transcribe -> reply -> speak
 * ============================================================================
 * This is the one tab that chains multiple modalities together on
 * purpose, the way a real voice assistant actually works: your recorded
 * voice (captured with the browser's MediaRecorder API) becomes text
 * (POST /transcribe), that text gets a reply (POST /chat), and the reply
 * becomes speech again — either read aloud entirely IN THE BROWSER via
 * `window.speechSynthesis` (free, no backend call at all for this step)
 * or generated by OpenAI's TTS API (POST /speak) for higher-quality audio.
 * ============================================================================
 */

"use client";

import { useRef, useState } from "react";
import type { ChatProvider, SpeechProvider, TtsProvider } from "@/lib/types";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

type Stage = "idle" | "recording" | "transcribing" | "thinking" | "speaking" | "done" | "error";

const STAGE_LABEL: Record<Stage, string> = {
  idle: "Press Record and say something",
  recording: "Recording… press Stop when done",
  transcribing: "Transcribing…",
  thinking: "Thinking of a reply…",
  speaking: "Speaking…",
  done: "Done — press Record to go again",
  error: "Something went wrong",
};

export default function VoicePanel() {
  const [sttProvider, setSttProvider] = useState<SpeechProvider>("local");
  const [ttsProvider, setTtsProvider] = useState<TtsProvider>("browser");
  const [chatProvider, setChatProvider] = useState<ChatProvider>("ollama");
  const [chatModel, setChatModel] = useState("llama3.2");

  const [stage, setStage] = useState<Stage>("idle");
  const [transcript, setTranscript] = useState<string | null>(null);
  const [reply, setReply] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const chunksRef = useRef<Blob[]>([]);

  async function startRecording() {
    setTranscript(null);
    setReply(null);
    setError(null);
    chunksRef.current = [];

    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const recorder = new MediaRecorder(stream);
      recorder.ondataavailable = (e) => chunksRef.current.push(e.data);
      recorder.onstop = () => {
        stream.getTracks().forEach((track) => track.stop());
        runPipeline(new Blob(chunksRef.current, { type: recorder.mimeType }));
      };
      recorder.start();
      mediaRecorderRef.current = recorder;
      setStage("recording");
    } catch {
      setError("Couldn't access the microphone — check your browser's permission prompt.");
      setStage("error");
    }
  }

  function stopRecording() {
    mediaRecorderRef.current?.stop();
  }

  async function runPipeline(audioBlob: Blob) {
    // Step 1: speech -> text
    setStage("transcribing");
    let text: string;
    try {
      const formData = new FormData();
      formData.append("audio", audioBlob, "recording.webm");
      formData.append("provider", sttProvider);
      const res = await fetch(`${API_URL}/transcribe`, { method: "POST", body: formData });
      const data = await res.json();
      if (data.error || !data.text) throw new Error(data.error ?? "No speech detected");
      text = data.text;
      setTranscript(text);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Transcription failed");
      setStage("error");
      return;
    }

    // Step 2: text -> reply
    setStage("thinking");
    let replyText: string;
    try {
      const res = await fetch(`${API_URL}/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, provider: chatProvider, model: chatModel }),
      });
      const data = await res.json();
      if (data.error || !data.reply) throw new Error(data.error ?? "No reply generated");
      replyText = data.reply;
      setReply(replyText);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Getting a reply failed");
      setStage("error");
      return;
    }

    // Step 3: reply -> speech
    setStage("speaking");
    try {
      if (ttsProvider === "browser") {
        // Entirely client-side — no backend call, no network request at all.
        const utterance = new SpeechSynthesisUtterance(replyText);
        await new Promise<void>((resolve) => {
          utterance.onend = () => resolve();
          utterance.onerror = () => resolve();
          window.speechSynthesis.speak(utterance);
        });
      } else {
        const res = await fetch(`${API_URL}/speak`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ text: replyText, voice: "alloy" }),
        });
        if (!res.ok) throw new Error(await res.text());
        const audioUrl = URL.createObjectURL(await res.blob());
        const audio = new Audio(audioUrl);
        await new Promise<void>((resolve) => {
          audio.onended = () => resolve();
          audio.onerror = () => resolve();
          audio.play();
        });
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Speaking the reply failed");
      setStage("error");
      return;
    }

    setStage("done");
  }

  const isBusy = stage === "transcribing" || stage === "thinking" || stage === "speaking";

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap gap-4 rounded-lg border border-black/10 dark:border-white/15 p-3 text-sm">
        <label className="flex items-center gap-2">
          <span className="opacity-70">Speech-to-text</span>
          <select
            value={sttProvider}
            onChange={(e) => setSttProvider(e.target.value as SpeechProvider)}
            className="rounded border border-black/10 dark:border-white/15 bg-transparent px-2 py-1"
          >
            <option value="local">local (faster-whisper, free)</option>
            <option value="openai">OpenAI Whisper</option>
          </select>
        </label>
        <label className="flex items-center gap-2">
          <span className="opacity-70">Reply from</span>
          <select
            value={chatProvider}
            onChange={(e) => setChatProvider(e.target.value as ChatProvider)}
            className="rounded border border-black/10 dark:border-white/15 bg-transparent px-2 py-1"
          >
            <option value="ollama">ollama (free, local)</option>
            <option value="openai">openai</option>
          </select>
          <input
            value={chatModel}
            onChange={(e) => setChatModel(e.target.value)}
            className="w-32 rounded border border-black/10 dark:border-white/15 bg-transparent px-2 py-1 text-xs"
          />
        </label>
        <label className="flex items-center gap-2">
          <span className="opacity-70">Text-to-speech</span>
          <select
            value={ttsProvider}
            onChange={(e) => setTtsProvider(e.target.value as TtsProvider)}
            className="rounded border border-black/10 dark:border-white/15 bg-transparent px-2 py-1"
          >
            <option value="browser">browser (free, client-side)</option>
            <option value="openai">OpenAI TTS</option>
          </select>
        </label>
      </div>

      <div className="flex items-center gap-3">
        {stage !== "recording" ? (
          <button
            onClick={startRecording}
            disabled={isBusy}
            className="rounded-lg bg-black px-5 py-2 text-sm font-medium text-white disabled:opacity-40 dark:bg-white dark:text-black"
          >
            ● Record
          </button>
        ) : (
          <button onClick={stopRecording} className="rounded-lg bg-red-600 px-5 py-2 text-sm font-medium text-white">
            ■ Stop
          </button>
        )}
        <span className="text-xs opacity-60">{STAGE_LABEL[stage]}</span>
      </div>

      {error && <p className="text-sm text-red-600 dark:text-red-400">{error}</p>}

      {transcript && (
        <div className="rounded-lg border border-black/10 dark:border-white/15 p-3 text-sm">
          <div className="mb-1 text-xs opacity-50">You said</div>
          {transcript}
        </div>
      )}
      {reply && (
        <div className="rounded-lg border border-black/10 dark:border-white/15 p-3 text-sm">
          <div className="mb-1 text-xs opacity-50">Reply</div>
          {reply}
        </div>
      )}
    </div>
  );
}
